### ISSUE TITLE
New GUID breaks pipeline

### ISSUE THREAD

**Issue by eltimn** [binxio/azure-devops-extensions#2]
I'm now getting the following error: 

> Step task reference is invalid. The task name GoogleCloudSdkInstaller is ambiguous. Specify one of the following identifiers to resolve the ambiguity: 73b17ce6-3f7b-4549-88b2-7d89f395bf94, 4de9a119-e4d8-4723-a7e7-8621554a0e2d

I assume this is due to the GUID changing (7323a0054c271e1d974752f0b71cb49684ab80ac). What was the reason for changing it?

**Comment by laurensknoll** [comment]
Sorry for that. I added a GcloudRunner and GsutilRunner task today and figured it would be nice to have sensible contribution names (see vss-extension.json). Changing the contribution name, however, required a new Guid.

I've reverted the contribution name and the guid. This is published with extension version 0.3.5. Please let me know if this resolves the ambiguity.

**Comment by laurensknoll** [comment]
Related PR: #4

**Comment by eltimn** [comment]
I'm still getting the same error.

I'm thinking since both of those GUIDs are in the system and tied to the task name (the name field in task.json), you may need to change both.

You could probably change the contribution name as well at the same time.

**Comment by eltimn** [comment]
Btw, the error message says: 

> Specify one of the following identifiers to resolve the ambiguity ...

As far as I can tell, there isn't a way to specify the identifier.

**Comment by laurensknoll** [comment]
So apparently extension updates keep the old contributions (for backward compatibility I assume), whilst uninstall/install removes the old contributions.. Because of this I've renamed and deprecated the old task. This resolves the ambiguity in my test-project.

I assume your Azure DevOps instance automatically updated the extension and this resolved the issue in your project also. If the issue persists, please uninstall/install the extension to get the deprecated contribution removed altogether.

**Comment by eltimn** [comment]
It appears to be working again. Thanks for getting it fixed.
